# Generated by Django 3.0 on 2020-05-16 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='descriptions',
            field=models.TextField(default='des'),
            preserve_default=False,
        ),
    ]
