# Generated by Django 3.0 on 2020-05-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200528_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='none', upload_to=''),
            preserve_default=False,
        ),
    ]
