# Generated by Django 3.0 on 2020-05-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_order_cupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupon',
            name='amount',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
