# Generated by Django 3.0 on 2020-05-31 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200530_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refer_code',
            field=models.CharField(default=12, max_length=20),
            preserve_default=False,
        ),
    ]
